name: 'Create Factory Tracking'
description: 'Creates tracking issue in Factory repo'
inputs:
  study_title:
    description: 'Study title'
    required: true
  lead_name:
    description: 'Study lead name'
    required: true
  lead_github:
    description: 'Study lead GitHub username'
    required: true
  target_date:
    description: 'Target completion date'
    required: true
  repo_url:
    description: 'Study repository URL'
    required: true
  already_collaborator:
    description: 'Whether study lead is already a collaborator'
    required: false
    default: 'false'
  invitation_sent:
    description: 'Whether collaboration invitation was sent'
    required: false
    default: 'false'
  org_token:
    description: 'Organization admin token'
    required: true

outputs:
  issue_url:
    description: 'Created issue URL'
    value: ${{ steps.create.outputs.issue_url }}
  issue_node_id:
    description: 'Issue node ID for project linking'
    value: ${{ steps.create.outputs.issue_node_id }}

runs:
  using: 'composite'
  steps:
    - name: Ensure study-tracking label exists
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.org_token }}
      run: |
        gh label create "study-tracking" \
          --description "Tracks individual study progress" \
          --color "0969da" \
          --repo "${{ github.repository }}" || echo "Label already exists"

    - name: Create tracking issue
      id: create
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.org_token }}
      run: |
        # Create tracking issue in Factory repo
        ISSUE_BODY=$(cat <<EOF
        ## ${{ inputs.study_title }}
        
        **Repository:** ${{ inputs.repo_url }}
        **Lead:** ${{ inputs.lead_name }} (@${{ inputs.lead_github }})
        **Target Date:** ${{ inputs.target_date }}
        **Status:** ðŸŸ¢ Active
        
        ### Current Stage
        - [x] Base Camp
        - [ ] Protocol Development
        - [ ] Phenotype Development
        - [ ] Analysis Specifications
        - [ ] Network Execution
        - [ ] Results Evaluation
        
        ### Activity
        Last updated: $(date -u +"%Y-%m-%d %H:%M UTC")
        
        ---
        *This issue tracks the study progress. Updates are automated.*
        EOF
        )
        
        # Determine assignment strategy based on collaborator status
        if [[ "${{ inputs.already_collaborator }}" == "true" ]]; then
          echo "âœ… @${{ inputs.lead_github }} is already a collaborator - attempting assignment..."
          
          ISSUE_URL=$(gh issue create \
            --repo "${{ github.repository }}" \
            --title "${{ inputs.study_title }}" \
            --body "$ISSUE_BODY" \
            --label "study-tracking" \
            --assignee "${{ inputs.lead_github }}")
          
          ASSIGNED_STATUS="(assigned to @${{ inputs.lead_github }})"
          
        elif [[ "${{ inputs.invitation_sent }}" == "true" ]]; then
          echo "ðŸ“¨ Collaboration invitation sent to @${{ inputs.lead_github }}"
          echo "â³ Creating issue without assignment (will work once they accept invitation)..."
          
          ISSUE_URL=$(gh issue create \
            --repo "${{ github.repository }}" \
            --title "${{ inputs.study_title }}" \
            --body "$ISSUE_BODY" \
            --label "study-tracking")
          
          ASSIGNED_STATUS="(invitation sent - can assign after acceptance)"
          
        else
          echo "âš ï¸  Could not invite @${{ inputs.lead_github }} as collaborator"
          echo "ðŸ”„ Creating issue without assignee..."
          
          ISSUE_URL=$(gh issue create \
            --repo "${{ github.repository }}" \
            --title "${{ inputs.study_title }}" \
            --body "$ISSUE_BODY" \
            --label "study-tracking")
          
          ASSIGNED_STATUS="(manual collaborator addition required)"
        fi
        
        # Get issue number and node_id
        ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -o '[0-9]*$')
        ISSUE_NODE_ID=$(gh api repos/${{ github.repository }}/issues/$ISSUE_NUMBER --jq '.node_id')
        
        echo "issue_url=$ISSUE_URL" >> $GITHUB_OUTPUT
        echo "issue_node_id=$ISSUE_NODE_ID" >> $GITHUB_OUTPUT
        echo "âœ… Factory tracking issue created: $ISSUE_URL $ASSIGNED_STATUS"