name: 'Create Study README'
description: 'Creates .github/README.md for study repository with objectives checklist and access instructions'
inputs:
  repo_name:
    description: 'Study repository name'
    required: true
  study_title:
    description: 'Study title for context'
    required: true
  lead_name:
    description: 'Study lead name'
    required: true
  lead_github:
    description: 'Study lead GitHub username'
    required: true
  factory_issue_number:
    description: 'Factory issue number for status updates'
    required: true
  project_url:
    description: 'Study project URL'
    required: true
  issues_data:
    description: 'JSON array of created status issues data'
    required: true
  org_token:
    description: 'Organization admin token'
    required: true

outputs:
  readme_created:
    description: 'Whether README was successfully created'
    value: ${{ steps.create_readme.outputs.readme_created }}

runs:
  using: 'composite'
  steps:
    - name: Create study README
      id: create_readme
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.org_token }}
        script: |
          console.log('DEBUG: Starting minimal test');
          
          console.log('DEBUG: repo_name = ' + "${{ inputs.repo_name }}");
          console.log('DEBUG: study_title = ' + "${{ inputs.study_title }}");
          console.log('DEBUG: issues_data length = ' + "${{ inputs.issues_data }}".length);
          console.log('DEBUG: issues_data preview = ' + "${{ inputs.issues_data }}".substring(0, 100));
          
          console.log('DEBUG: Minimal test completed');
          core.setOutput('readme_created', 'true');