name: 'Create Study README'
description: 'Creates .github/README.md for study repository with objectives checklist and access instructions'
inputs:
  repo_name:
    description: 'Study repository name'
    required: true
  study_title:
    description: 'Study title for context'
    required: true
  lead_name:
    description: 'Study lead name'
    required: true
  lead_github:
    description: 'Study lead GitHub username'
    required: true
  factory_issue_number:
    description: 'Factory issue number for status updates'
    required: true
  project_url:
    description: 'Study project URL'
    required: true
  issues_data:
    description: 'JSON array of created status issues data'
    required: true
  org_token:
    description: 'Organization admin token'
    required: true

outputs:
  readme_created:
    description: 'Whether README was successfully created'
    value: ${{ steps.create_readme.outputs.readme_created }}

runs:
  using: 'composite'
  steps:
    - name: Create study README
      id: create_readme
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.org_token }}
        script: |
          const fs = require('fs');
          
          console.log('Starting README creation');
          
          const repoOwner = "${{ github.repository_owner }}";
          const repoName = "${{ inputs.repo_name }}";  
          const studyTitle = "${{ inputs.study_title }}";
          const leadName = "${{ inputs.lead_name }}";
          const leadGithub = "${{ inputs.lead_github }}";
          const factoryIssueNumber = "${{ inputs.factory_issue_number }}";
          const projectUrl = "${{ inputs.project_url }}";
          const factoryRepo = "${{ github.repository }}";
          const issuesDataJson = "${{ inputs.issues_data }}";
          
          console.log('Variables initialized');
          
          // Parse the issues data
          let issuesData;
          try {
            issuesData = JSON.parse(issuesDataJson);
            console.log('Parsed issues data: ' + issuesData.length + ' items');
          } catch (parseError) {
            console.error('Parse error: ' + parseError.message);
            core.setFailed('Failed to parse issues data: ' + parseError.message);
            return;
          }
          
          // Generate objectives checklist  
          const objectivesList = [];
          for (let i = 0; i < issuesData.length; i++) {
            const issue = issuesData[i];
            const line = '- [ ] **' + issue.title + '** #' + issue.number;
            objectivesList.push(line);
          }
          const objectivesChecklist = objectivesList.join('\n');
          
          console.log('Generated objectives checklist');
          
          // Read template and create content
          try {
            const template = fs.readFileSync('.github/templates/study-readme.md', 'utf8');
            
            let readmeContent = template;
            readmeContent = readmeContent.replace(/\{\{STUDY_TITLE\}\}/g, studyTitle);
            readmeContent = readmeContent.replace(/\{\{OBJECTIVES_CHECKLIST\}\}/g, objectivesChecklist);
            readmeContent = readmeContent.replace(/\{\{PROJECT_URL\}\}/g, projectUrl);
            readmeContent = readmeContent.replace(/\{\{FACTORY_ISSUE_NUMBER\}\}/g, factoryIssueNumber);
            readmeContent = readmeContent.replace(/\{\{FACTORY_REPO\}\}/g, factoryRepo);
            readmeContent = readmeContent.replace(/\{\{LEAD_GITHUB\}\}/g, leadGithub);
            readmeContent = readmeContent.replace(/\{\{LEAD_NAME\}\}/g, leadName);
            readmeContent = readmeContent.replace(/\{\{CREATION_DATE\}\}/g, new Date().toISOString().split('T')[0]);
            
            console.log('Template processed');
            
            // Create the README file
            const createResponse = await github.rest.repos.createOrUpdateFileContents({
              owner: repoOwner,
              repo: repoName,
              path: '.github/README.md',
              message: 'Add study README with objectives and access instructions',
              content: Buffer.from(readmeContent).toString('base64'),
              committer: {
                name: 'GitHub Action',
                email: 'action@github.com'
              },
              author: {
                name: 'Factory Study System', 
                email: 'action@github.com'
              }
            });
            
            console.log('README created successfully');
            core.setOutput('readme_created', 'true');
            
          } catch (error) {
            console.error('Error: ' + error.message);
            core.setFailed('Failed to create README: ' + error.message);
          }