name: 'Create Study README'
description: 'Creates .github/README.md for study repository with objectives checklist and access instructions'
inputs:
  repo_name:
    description: 'Study repository name'
    required: true
  study_title:
    description: 'Study title for context'
    required: true
  lead_name:
    description: 'Study lead name'
    required: true
  lead_github:
    description: 'Study lead GitHub username'
    required: true
  factory_issue_number:
    description: 'Factory issue number for status updates'
    required: true
  project_url:
    description: 'Study project URL'
    required: true
  issues_data:
    description: 'JSON array of created status issues data'
    required: true
  org_token:
    description: 'Organization admin token'
    required: true

outputs:
  readme_created:
    description: 'Whether README was successfully created'
    value: ${{ steps.create_readme.outputs.readme_created }}

runs:
  using: 'composite'
  steps:
    - name: Create study README
      id: create_readme
      uses: actions/github-script@v7
      env:
        REPO_NAME: ${{ inputs.repo_name }}
        STUDY_TITLE: ${{ inputs.study_title }}
        LEAD_NAME: ${{ inputs.lead_name }}
        LEAD_GITHUB: ${{ inputs.lead_github }}
        FACTORY_ISSUE_NUMBER: ${{ inputs.factory_issue_number }}
        PROJECT_URL: ${{ inputs.project_url }}
        ISSUES_DATA: ${{ inputs.issues_data }}
        FACTORY_REPO: ${{ github.repository }}
        REPO_OWNER: ${{ github.repository_owner }}
      with:
        github-token: ${{ inputs.org_token }}
        script: |
          console.log('DEBUG: Starting with environment variables');
          
          const repoName = process.env.REPO_NAME;
          const studyTitle = process.env.STUDY_TITLE;
          const leadName = process.env.LEAD_NAME;
          const leadGithub = process.env.LEAD_GITHUB;
          const factoryIssueNumber = process.env.FACTORY_ISSUE_NUMBER;
          const projectUrl = process.env.PROJECT_URL;
          const issuesDataJson = process.env.ISSUES_DATA;
          const factoryRepo = process.env.FACTORY_REPO;
          const repoOwner = process.env.REPO_OWNER;
          
          console.log('DEBUG: repo_name = ' + repoName);
          console.log('DEBUG: study_title = ' + studyTitle);
          console.log('DEBUG: issues_data length = ' + issuesDataJson.length);
          
          core.setOutput('readme_created', 'true');