name: 'Update Workflow Dropdown'
description: 'Updates the provision-study workflow dropdown with current study leads'
inputs:
  workflow_path:
    description: 'Path to the workflow file to update'
    required: true
    default: '.github/workflows/provision-study.yml'

runs:
  using: 'composite'
  steps:
    - name: Update dropdown options
      shell: bash
      run: |
        echo "🔍 Starting workflow dropdown update..."
        
        # Check if study leads file exists
        if [[ ! -f .github/data/study-leads.json ]]; then
          echo "❌ No study leads file found, skipping update"
          exit 0
        fi
        
        echo "📖 Reading study leads from JSON..."
        cat .github/data/study-leads.json
        
        # Count study leads
        LEAD_COUNT=$(jq '.study_leads | length' .github/data/study-leads.json)
        echo "📊 Found $LEAD_COUNT study leads"
        
        if [[ $LEAD_COUNT -eq 0 ]]; then
          echo "⚠️  No study leads found, keeping only 'Add new study lead' option"
          OPTIONS_CONTENT="          - 'Add new study lead'"
        else
          echo "🔄 Generating dropdown options..."
          
          # Start with "Add new study lead" as default first option
          OPTIONS_CONTENT="          - 'Add new study lead'"
          
          # Generate dropdown options from JSON and add beneath
          while IFS= read -r line; do
            NAME=$(echo "$line" | jq -r '.name')
            GITHUB=$(echo "$line" | jq -r '.github_username')
            echo "  Processing: $NAME ($GITHUB)"
            
            # Escape single quotes in name for YAML
            ESCAPED_NAME=$(echo "$NAME" | sed "s/'/''/g")
            OPTIONS_CONTENT="${OPTIONS_CONTENT}\n          - '${ESCAPED_NAME}|${GITHUB}'"
          done < <(jq -c '.study_leads[]' .github/data/study-leads.json)
        fi
        
        echo "📝 Generated options:"
        echo -e "$OPTIONS_CONTENT"
        
        # Update workflow using simple line-by-line approach
        echo "🔧 Updating workflow file..."
        
        # Write new options to temp file
        echo -e "$OPTIONS_CONTENT" > /tmp/new_options.txt
        
        # Use sed to replace the options section directly
        sed '/^        options:$/,/^      [a-zA-Z]/ {
          /^        options:$/ {
            p
            r /tmp/new_options.txt
            d
          }
          /^      [a-zA-Z]/ !d
        }' "${{ inputs.workflow_path }}" > /tmp/workflow_temp.yml
        
        echo "🔍 Checking if replacement was successful..."
        if grep -q "Sean O" /tmp/workflow_temp.yml; then
          echo "✅ Found Sean O in updated file"
        else
          echo "❌ Sean O not found in updated file"
        fi
        
        # Replace original file
        mv /tmp/workflow_temp.yml "${{ inputs.workflow_path }}"
        echo "✅ Successfully updated workflow dropdown"
        
        # Cleanup
        rm -f /tmp/new_options.txt