name: Study Status Update Webhook

on:
  workflow_call:
    inputs:
      factory_issue_number:
        description: 'Factory issue number to update'
        required: true
        type: string
      factory_repository:
        description: 'Factory repository (owner/repo)'
        required: false
        type: string
        default: 'seanr87/Factory'
    secrets:
      FACTORY_ORG_TOKEN:
        description: 'Token for Factory repository access'
        required: true

permissions:
  contents: read

jobs:
  update-factory-objective:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'status-tracking')
    steps:
      - name: Update Factory Objective field
        uses: seanr87/Factory/.github/actions/trigger-factory-status-update@main
        with:
          issue_title: ${{ github.event.issue.title }}
          issue_url: ${{ github.event.issue.html_url }}
          issue_labels: ${{ toJson(github.event.issue.labels) }}
          issue_action: ${{ github.event.action }}
          factory_issue_number: ${{ inputs.factory_issue_number }}
          study_repo: ${{ github.repository }}
          factory_org_token: ${{ secrets.FACTORY_ORG_TOKEN }}